# 環境変数
#  * MACKEREL_APIKEY
#    * https://mackerel.io/ja/docs/entry/advanced/cli
#  * SSH_KEY_FINGERPRINT
#    * https://mackerel.io/ja/docs/entry/advanced/cli

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    environment:
      - SSH_KEY_FINGERPRINT: foo
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT

      - checkout

      - run: ls ~/.ssh/

      # - run:
      #     name: install mkr
      #     command: |
      #       cd /tmp
      #       wget https://github.com/mackerelio/mkr/releases/download/v0.32.0/mkr_linux_amd64.tar.gz
      #       tar -xvzf mkr_linux_amd64.tar.gz
      #       sudo cp mkr_linux_amd64/mkr /usr/local/bin/mkr
      #       sudo chmod 755 /usr/local/bin/mkr
      #       cd -

      # - run: mkr hosts

      # - run: git --version
      # - run: ssh git@github.com || true
      # - run: cat README.md
      # - run: echo "- $(date)" >> README.md
      # - run: cat README.md
      # - run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"
      # - run: |
      #     git commit -am '[ci skip] update from Circle CI!'
      #     git push
